name: Publish Digital Garden

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout content repository
        uses: actions/checkout@v4

      - name: Build with quartz-hoster
        run: |
          git clone --depth 1 https://github.com/lcorcodilos/quartz-hoster.git quartz-hoster
          rm -rf quartz-hoster/content/*
          rsync -av --exclude="quartz-hoster/*" --include='*.md' --include="**/" --exclude="*" --prune-empty-dirs . quartz-hoster/content/
          mv .quartz.config quartz-hoster/quartz.config.ts
          cd quartz-hoster
          docker compose run --rm app npx quartz build
          ls public/*
          cd ../
          cp -r quartz-hoster/public ./output
          touch ./output/.nojekyll
          ls ./output

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./quartz-hoster/public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
