name: Publish Digital Garden

on:
  push:
    branches: 
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git info
          repository: lcorcodilos/quartz-hoster
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git info
          path: digital-garden/
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Dependencies
        run: npm ci
      - name: Build Quartz
        run: |
            cp digital-garden/.quartz/quartz.config.ts quartz.config.ts
            chmod 755 digital-garden/.quartz/theme_setup.sh
            ./digital-garden/.quartz/theme_setup.sh
            ls 
            ls quartz
            ls digitial-garden/.quartz/_index.scss
            mv digitial-garden/.quartz/_index.scss quartz/styles/themes/_index.scss
            rsync -av --include='*.md' --include="**/" --exclude="*" --prune-empty-dirs digital-garden/ content/
            npx quartz build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
